### ISSUE TITLE
Temperature sensor reading

### ISSUE THREAD

**Issue by luka1983** [luka1983/beer_tc#1]
Temperature reading from 1-wire sensor ds18b20 - code architecture and implementation.

**Comment by matijaGP** [comment]
I've added avr-ds18b20-lib branch, and demo code for reading temperature sensor, notably, this commit is of interest: b013d352b0e397ed7159e6550c3e9e7ef46019f1

Should we add reading of the temperature in tcontrol.c ?

**Comment by luka1983** [comment]
Yes, and I also think it makes sense to have temp sensor read implemented as a separate module (e.g. tread.h/c). So we just need this module to expose single reading func e.g. uint16_t get_temp_read() or something like that.

**Comment by luka1983** [comment]
We should also implement temperature read via interrupt. The small problem here is that we're already using 16-bit timer for temperature control loop, so getting 1s with 8-bit will require some local counter also.

The other possibility  is to trigger new sensor read when temperature is read by control loop, and just return the reading triggered from previous request.

**Comment by matijaGP** [comment]
Ok

**Comment by matijaGP** [comment]
Why not read temperature in the control loop itself?

**Comment by luka1983** [comment]
I just thought that it would be neat to have these processes in separate threads, but there is probably no real need for this, and your solution is also cleaner. That was also the second possibility I've mentioned above.
